apiVersion: v1
kind: Service
metadata:
    name: app-svc
    namespace: django-on-k8s
    labels:
        app: app-svc
spec:
    ports:
        - port: 8000
          targetPort: 8000
    selector:
        app: django-application