apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
    namespace: django-on-k8s
    labels:
        app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx
              readOnly: true
            - mountPath: "/data/static"
              name: staticfiles
      volumes:
        - name: nginx
          configMap:
            name: nginx-cm
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc