apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    namespace: django-on-k8s
    labels:
        app: nginx-svc
spec:
    type: NodePort
    ports:
      - port: 80
        nodePort: 30005
        targetPort: 80
    selector:
        app: nginx