apiVersion: v1
kind: ConfigMap
metadata:
    name: db-secret-credentials
    namespace: django-on-k8s
    labels:
        app: postgres
data:
    POSTGRES_USER: django-user
    POSTGRES_PASSWORD: django-password
    POSTGRES_DB: django-db