apiVersion: v1
kind: Service
metadata:
    name: postgres-svc
    namespace: django-on-k8s
    labels:
        app: postgres-svc
spec:
    type: NodePort
    ports:
        - port: 5432
          targetPort: 5432
          nodePort: 30004
    selector:
        app: postgresdb